name: sync-gitee
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitee.com:Leebiger/scripts.git
          ssh_private_key:
            ${{ secrets.GITEE_KEY }}
